### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by ivan132465798** [LumenResearch/heatmappy#5]
I´m trying to create a heatmap on my video.

My video is too large, and my vector of points also big. When I run my program, it gives me a Memory Error. I think the error is because i´m returning a list(heatmap_clips) and it occupies the entire memory.

Can you help solving this problem please?

Thanks

**Comment by FrancescoScarlata** [comment]
I have the same problem with a video of 1 minute  :/

EDIT: works on a minute with the 64bit python, with 32 it's a nope

**Comment by AndrewNappin-lumen** [comment]
Solved in latest updates
